import "#/styles/globals.css";
import type {Metadata} from "next";
import {Rubik} from "next/font/google";

const rubik = Rubik({
  weight: ["300", "500", "700", "900"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Device Manager App",
  description: "Generated by create next app"
};

export default function RootLayout({children}: LayoutProps<"/">) {
  return (
    <html dir="rtl" lang="fa" className={`dark antialiased ${rubik.variable}`}>
      <body>{children}</body>
    </html>
  );
}
